### ISSUE TITLE
NoClassDefFoundError: org/graylog/plugins/pipelineprocessor/ast/functions/Function

### ISSUE THREAD

**Issue by omercnet** [Graylog2/graylog-example-plugin-function-strlen#1]
Hi guys,

Going through the post [here](https://www.graylog.org/blog/71-writing-your-own-graylog-processing-pipeline-functions) build a pipeline plugin I get this error when loading graylog-server with the new jar.

``` java
INFO : org.graylog2.bootstrap.CmdLineTool - Loaded plugin: User-Agent Parser 1.0.0-SNAPSHOT [com.omercnet.graylog2.uaparser.UaParserFunctionPlugin]
INFO : org.graylog2.bootstrap.CmdLineTool - Loaded plugin: Elastic Beats Input 1.1.1 [org.graylog.plugins.beats.BeatsInputPlugin]
INFO : org.graylog2.bootstrap.CmdLineTool - Loaded plugin: Collector 1.1.1 [org.graylog.plugins.collector.CollectorPlugin]
INFO : org.graylog2.bootstrap.CmdLineTool - Loaded plugin: Enterprise Integration Plugin 1.1.1 [org.graylog.plugins.enterprise_integration.EnterpriseIntegrationPlugin]
INFO : org.graylog2.bootstrap.CmdLineTool - Loaded plugin: MapWidgetPlugin 1.1.1 [org.graylog.plugins.map.MapWidgetPlugin]
INFO : org.graylog2.bootstrap.CmdLineTool - Loaded plugin: Pipeline Processor Plugin 1.1.1 [org.graylog.plugins.pipelineprocessor.ProcessorPlugin]
INFO : org.graylog2.bootstrap.CmdLineTool - Loaded plugin: Anonymous Usage Statistics 2.1.1 [org.graylog.plugins.usagestatistics.UsageStatsPlugin]
INFO : org.graylog2.bootstrap.CmdLineTool - Running with JVM arguments: -Xms1g -Xmx2g -XX:NewRatio=1 -XX:MaxMetaspaceSize=256m -XX:+ResizeTLAB -XX:+UseConcMarkSweepGC -XX:+CMSConcurrentMTEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseParNewGC -XX:-OmitStackTraceInFastThrow -Dlog4j.configurationFile=/usr/share/graylog/data/config/log4j2.xml -Djava.library.path=/usr/share/graylog/lib/sigar/ -Dgraylog2.installation_source=docker
Exception in thread "main" java.lang.NoClassDefFoundError: org/graylog/plugins/pipelineprocessor/ast/functions/Function
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:814)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at com.omercnet.graylog2.uaparser.UaParserFunctionModule.configure(UaParserFunctionModule.java:22)
    at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
    at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
    at org.graylog2.shared.bindings.PluginBindings.configure(PluginBindings.java:51)
    at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
    at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
    at com.google.inject.spi.Elements.getElements(Elements.java:110)
    at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
    at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
    at com.google.inject.Guice.createInjector(Guice.java:99)
    at org.graylog2.shared.bindings.Hk2GuiceBridgeJitInjector.create(Hk2GuiceBridgeJitInjector.java:60)
    at org.graylog2.shared.bindings.GuiceInjectorHolder.createInjector(GuiceInjectorHolder.java:32)
    at org.graylog2.bootstrap.CmdLineTool.setupInjector(CmdLineTool.java:379)
    at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:193)
    at org.graylog2.bootstrap.Main.main(Main.java:44)
Caused by: java.lang.ClassNotFoundException: org.graylog.plugins.pipelineprocessor.ast.functions.Function
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:814)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 27 more
```

my code is here https://github.com/omercnet/graylog2-uaparser/tree/master/src/main/java/com/omercnet/graylog2/uaparser
any ideas?

**UPDATE: went over the plugin code here and copied a lot that wasn't mentioned in the blog post but still getting the same error**

**Comment by omercnet** [comment]
my solution was to add `graylog-plugin-pipeline-processor` to the package but I'm not sure that's what you guys meant :/

``` xml
        <dependency>
            <groupId>org.graylog.plugins</groupId>
            <artifactId>graylog-plugin-pipeline-processor</artifactId>
            <version>1.1.1</version>
            <scope>compile</scope>
        </dependency>
```

**Comment by joschi** [comment]
@omercnet Make sure that the Pipeline Processor plugin has been loaded by Graylog. You own plugin should use the `org.graylog.plugins:graylog-plugin-pipeline-processor` artifact in the `provided` scope.

**Comment by omercnet** [comment]
@joschi it is being loaded but my plugin loads first
is there a way to control the loading order? could it be alphabetically by the groupid ?

```
graylog_1  | 2016-09-25 06:10:30,696 INFO : org.graylog2.bootstrap.CmdLineTool - Loaded plugin: User-Agent Parser 1.0.0-SNAPSHOT [com.omercnet.graylog2.uaparser.UaParserFunctionPlugin]
graylog_1  | 2016-09-25 06:10:30,697 INFO : org.graylog2.bootstrap.CmdLineTool - Loaded plugin: Elastic Beats Input 1.1.1 [org.graylog.plugins.beats.BeatsInputPlugin]
graylog_1  | 2016-09-25 06:10:30,697 INFO : org.graylog2.bootstrap.CmdLineTool - Loaded plugin: Collector 1.1.1 [org.graylog.plugins.collector.CollectorPlugin]
graylog_1  | 2016-09-25 06:10:30,698 INFO : org.graylog2.bootstrap.CmdLineTool - Loaded plugin: Enterprise Integration Plugin 1.1.1 [org.graylog.plugins.enterprise_integration.EnterpriseIntegrationPlugin]
graylog_1  | 2016-09-25 06:10:30,698 INFO : org.graylog2.bootstrap.CmdLineTool - Loaded plugin: MapWidgetPlugin 1.1.1 [org.graylog.plugins.map.MapWidgetPlugin]
graylog_1  | 2016-09-25 06:10:30,698 INFO : org.graylog2.bootstrap.CmdLineTool - Loaded plugin: Pipeline Processor Plugin 1.1.1 [org.graylog.plugins.pipelineprocessor.ProcessorPlugin]
graylog_1  | 2016-09-25 06:10:30,698 INFO : org.graylog2.bootstrap.CmdLineTool - Loaded plugin: Anonymous Usage Statistics 2.1.1 [org.graylog.plugins.usagestatistics.UsageStatsPlugin]
graylog_1  | 2016-09-25 06:10:30,791 INFO : org.graylog2.bootstrap.CmdLineTool - Running with JVM arguments: -Xms1g -Xmx2g -XX:NewRatio=1 -XX:MaxMetaspaceSize=256m -XX:+ResizeTLAB -XX:+UseConcMarkSweepGC -XX:+CMSConcurrentMTEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseParNewGC -XX:-OmitStackTraceInFastThrow -Dlog4j.configurationFile=/usr/share/graylog/data/config/log4j2.xml -Djava.library.path=/usr/share/graylog/lib/sigar/ -Dgraylog2.installation_source=docker
```

**Comment by joschi** [comment]
@omercnet Thanks for reporting this!

There was an error in this example's `graylog-plugin.properties` file (see 73295489d808e50f42bc2a1085a5d641fb10cb14).

**Comment by omercnet** [comment]
awesome, thanks!

please keep in mind the original blog post is missing lots of other code pieces (like dependencies) that I had to copy from this repo, one cannot write a working plugin based solely on the blog post :(

**Comment by joschi** [comment]
@omercnet That's intentional (kind of) as it would make the blog post really long.
